// USUARIO
POST https://musical-awards.herokuapp.com/user/signup
Content-Type: application/json

{
   "name":"igor",
   "email":"igor@gmail.com",
   "password":"123456",
   "roles": "ADMIN"  
}

###
# @name login
POST https://musical-awards.herokuapp.com/user/login
Content-Type: application/json

{
   "email":"igor@gmail.com",
   "password":"123456"
}

### tickets --------------------------------------
POST https://musical-awards.herokuapp.com/ticket/create
Content-Type: application/json
Authorization: {{login.response.body.Token}}

{
   "showId":"c8f83713-90b8-4b0c-bf9e-de34c90375eb"
}

### 
DELETE  https://musical-awards.herokuapp.com/ticket/delete/c8f83713-90b8-4b0c-bf9e-de34c90375eb
Authorization: {{login.response.body.Token}}


### SHOW ------------------------------------------------------

POST https://musical-awards.herokuapp.com/show/create
Content-Type: application/json
Authorization: {{login.response.body.Token}}

{
   "starts":"08/12/2022",
   "band":"engenheiros do havai"
}

###
GET https://musical-awards.herokuapp.com/show/


